### ISSUE TITLE
Small detail for Sap flow Rate calculation

### ISSUE THREAD

**Issue by hannahjames77** [mcwimm/SFA#2]
![image](https://user-images.githubusercontent.com/62958704/87806040-e3d0b700-c81b-11ea-911e-8fc0ee996d00.png)
Unless all three methods are selected, no graph appears
![image](https://user-images.githubusercontent.com/62958704/87806139-0793fd00-c81c-11ea-93f0-ccddaa514dc4.png)

**Comment by mcwimm** [comment]
fixed
